---
- hosts: localhost
  connection: local
  become: true

  tasks:

  - name: apt update
    apt:
      update_cache: yes

  - name: apt upgrade
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: apt install qemu-guest-agent
    ansible.builtin.apt:
      name: qemu-guest-agent
      state: latest

  - name: Disable predictable device naming
    ansible.builtin.lineinfile:
      path: /etc/default/grub
      regexp: 'GRUB_CMDLINE_LINUX=""'
      line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'

  - name: /usr/sbin/update-grub
    command: /usr/sbin/update-grub

  - name: Install /etc/netplan/00-installer-config.yaml
    ansible.builtin.copy:
      src: files/00-installer-config.yaml
      dest: /etc/netplan/00-installer-config.yaml

  - name: Remove SSH host keys
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/ssh/ssh_host_dsa_key
      - /etc/ssh/ssh_host_dsa_key.pub
      - /etc/ssh/ssh_host_ecdsa_key
      - /etc/ssh/ssh_host_ecdsa_key.pub
      - /etc/ssh/ssh_host_ed25519_key
      - /etc/ssh/ssh_host_ed25519_key.pub
      - /etc/ssh/ssh_host_rsa_key
      - /etc/ssh/ssh_host_rsa_key.pub

  - name: /usr/bin/cloud-init clean
    command: /usr/bin/cloud-init clean

  - name: /usr/sbin/logrotate -f /etc/logrotate.conf
    command: /usr/sbin/logrotate -f /etc/logrotate.conf
