# This is the network config written by 'subiquity'
network:
  ethernets:
    eth0:
      dhcp4: true
#      addresses:
#      -
#      gateway4:
      nameservers:
        addresses:
        - 10.10.10.10
        search:
        - charlietango.com
  version: 2
